author: DuSuWen # 作者
description: DuSuWen's blog
keyword: hexo-theme, vuejs
favicon:

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
 Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: false

# qrcode
qrcode: false

# comment
# you can set gitment, uyan or disqus

comment:

# gitment config
gitment_owner: yanm1ng
gitment_repo: yanm1ng.github.io
gitment_oauth_id: 0f87e490e00ee3fd87ef
gitment_oauth_secret: 4a9d2b148e7971c2201ad12131ce8bf8159ccd2e

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id:

# disqus config
disqus_shortname:

about:
  banner: https://pic1.zhimg.com/80/v2-ad6b4909967ec291903e8af93c211f54_r.jpg
  avatar: https://avatars0.githubusercontent.com/u/15500093?s=460&v=4
  description: ""
  weibo_username:
  twitter_username:
  github_username: DusuWen
  zhihu_username:
  douban_username:
  linkedin_username:

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML
